source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

platform :ios, '12.0'
inhibit_all_warnings!
use_modular_headers!

# 设置所有Pod的部署目标版本
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

target 'Bunnyx' do

  pod 'AFNetworking', '~> 4.0'
  pod 'SDWebImage','5.19.2',:modular_headers => true
  pod 'Masonry'
  pod 'MJRefresh'
end
